### ISSUE TITLE
Prepare for 1.0.2.RELEASE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/python#16]
As a developer, I'd like to release 1.0.2 version of the app with the recent improvements and bug-fixes.

**Comment by artembilan** [comment]
The PR #15 has been merged.

Looks like we are ready to release `1.0.2`.

**Comment by sabbyanandan** [comment]
@sobychacko: Could you help with the release, please?

**Comment by sabbyanandan** [comment]
This is complete.
